# .github/workflows/main.yml
name: Build and Deploy Static Site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /latest-next-portfolio
      API_URL: next-portfolio-juliansuringas-projects.vercel.app
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build and Export
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - name: Print Environment Variables
        run: |
          echo "NEXT_PUBLIC_BASE_PATH: $NEXT_PUBLIC_BASE_PATH"
          echo "NODE_ENV: $NODE_ENV"
          echo "API_URL: $API_URL"
